### ISSUE TITLE
devices created with old VisiCut version?

### ISSUE THREAD

**Issue by reallinkD** [fablabnbg/visicut-settings#1]
Starting the downloadable zip of version latest (1.7.9-51-g79ed49b) in the console and choosing this repository's default settings gives the following errors:

`E:\visicut>java -jar Visicut.jar`

`java.lang.IllegalArgumentException: Unsupported element: laserDevice`
`Continuing ...`
`Error reading: C:\Users\Adelbert Klein\.visicut\devices\Schneidplotter_32_Nuelan
d.xml. Invalid File Format (created with old VisiCut version?)`

`java.lang.IllegalArgumentException: Unsupported element: laserDevice`
`Continuing ...`
`Error reading: C:\Users\Adelbert Klein\.visicut\devices\Silhouette_32_Cameo.xml.
 Invalid File Format (created with old VisiCut version?)`

**Comment by jnweiger** [comment]
@reallinkD please try the latest 1.8. build of Visicut.
